#!/usr/bin/env php
<?php
/**
 * Este archivo forma parte del Framework Nimter.
 *
 * Para más información acerca de los derechos de autor y la licencia, ver el archivo LICENSE.
 *
 * PHP versión 7.1.3
 *
 * @author Alexis Mora <alexis.mora1v@gmail.com>
 * @version 1.3.0
 */

require_once('Nimter/autoload.php');
require_once('Nimter/vendor/autoload.php');

//Carga la configuracion del framework
$dotenv = \Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

use Nimter\Lina\Lina;

$lina = new Lina($argv);
