#!/usr/bin/env php
<?php
/**
 * Este archivo forma parte del Framework Nimter.
 *
 * Para más información acerca de los derechos de autor y la licencia, ver el archivo LICENSE.
 *  
 * PHP versión 7.1.3
 *
 * @package Nimter\Core\controllers
 * @author Alexis Mora <alexis.mora1v@gmail.com>
 * @version 1.2.0
 */

require_once('Nimter/autoload.php');
require_once('Nimter/vendor/autoload.php');

use Nimter\Core\lina\lina;

$lina = new lina($argv);
?> 